# GENERATED - DO NOT EDIT THIS FILE DIRECTLY
openapi: 3.0.3
{{- $spec := (ds "spec") }}

servers:
  - url: https://demo.secapi.cloud/providers/seca.{{ $spec.name }}
    description: Path Schema
  - url: https://{{ $spec.name }}.seca.demo.secapi.cloud
    description: DNS Schema

info:
  title: Sovereign European Cloud API - {{ $spec.title }}
  version: {{ $spec.version }}
  description: |
{{ $spec.description | strings.TrimSpace | indent 4 }}

security:
  - bearerAuth: []

tags:
{{- range $spec.resources }}
  - name: {{ .name | strings.Title }}
    description: {{ .name | strings.Title }} management
{{- end }}

paths:
{{- range $spec.resources }}
  {{- if coll.Has .operations "list" }}
  /{{ $spec.version }}/{{ if .tenant }}tenants/{id}/{{ end }}{{ if .workspace }}workspaces/{workspace}/{{ end }}{{ if and (coll.Has . "lan") .lan }}lans/{lan}/{{ end }}{{ .plural | strings.Slug }}:
    get:
      tags:
        - {{ .name | strings.Title }}
      security:
        - bearerAuth: []
      summary: List {{ .plural }}
      {{- if and (coll.Has . "description") (coll.Has .description "list") }}
      description: |
{{ .description.list | strings.TrimSpace | indent 8 }}
      {{- end }}
      operationId: list{{ .plural | strings.Title | strings.ReplaceAll " " "" }}
      parameters:
      {{- if .tenant }}
        - $ref: './schemas/parameters.yaml#/parameters/tenantID'
      {{- end }}
      {{- if .workspace }}
        - $ref: './schemas/parameters.yaml#/parameters/workspaceName'
      {{- end }}
        - $ref: './schemas/parameters.yaml#/parameters/labelSelector'
        - $ref: './schemas/parameters.yaml#/parameters/limitParam'
        - $ref: './schemas/parameters.yaml#/parameters/skipTokenParam'
        - $ref: './schemas/parameters.yaml#/parameters/acceptHeader'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/{{ .name | strings.Title | strings.ReplaceAll " " "" }}Iterator"
              {{- if and (coll.Has . "example") (coll.Has .example "list") }}
              example:
{{ .example.list | data.ToYAML | indent 16 }}
              {{- end }}
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'
  {{ end }}
  {{- if or (coll.Has .operations "get") (coll.Has .operations "put") (coll.Has .operations "delete") }}
  /{{ $spec.version }}/{{ if .tenant }}tenants/{id}/{{ end }}{{ if .workspace }}workspaces/{workspace}/{{ end }}{{ if and (coll.Has . "lan") .lan }}lans/{lan}{{ end }}{{ .plural | strings.Slug  }}/{name}:
  {{- if coll.Has .operations "get" }}
    get:
      tags:
        - {{ .name | strings.Title }}
      security:
        - bearerAuth: []
      summary: Get a specific {{ .name }}
      {{- if and (coll.Has . "description") (coll.Has .description "get") }}
      description: |
{{ .description.get | strings.TrimSpace | indent 8 }}
      {{- end }}
      operationId: get{{ .name | strings.Title | strings.ReplaceAll " " "" }}
      parameters:
      {{- if .tenant }}
        - $ref: './schemas/parameters.yaml#/parameters/tenantID'
      {{- end }}
      {{- if .workspace }}
        - $ref: './schemas/parameters.yaml#/parameters/workspaceName'
      {{- end }}
        - $ref: './schemas/parameters.yaml#/parameters/resourceName'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '{{ .schema }}'
              {{- if and (coll.Has . "example") (coll.Has .example "get") }}
              example:
{{ .example.get | data.ToYAML | indent 16 }}
              {{- end }}
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '404':
          $ref: './schemas/errors.yaml#/responses/Error404'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'
    {{ end }}
    {{- if coll.Has .operations "put" }}
    put:
      tags:
        - {{ .name | strings.Title }}
      security:
        - bearerAuth: []
      summary: Create or update a {{ .name }}
      {{- if and (coll.Has . "description") (coll.Has .description "put") }}
      description: |
{{ .description.put | strings.TrimSpace | indent 8 }}
      {{- end }}
      operationId: createOrUpdate{{ .name | strings.Title | strings.ReplaceAll " " "" }}
      parameters:
      {{- if .tenant }}
        - $ref: './schemas/parameters.yaml#/parameters/tenantID'
      {{- end }}
      {{- if .workspace }}
        - $ref: './schemas/parameters.yaml#/parameters/workspaceName'
      {{- end }}
        - $ref: './schemas/parameters.yaml#/parameters/resourceName'
        - $ref: './schemas/parameters.yaml#/parameters/ifUnmodifiedSince'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '{{ .schema }}'
              {{- if and (coll.Has . "example") (coll.Has .example "putRequest") }}
              example:
{{ .example.putRequest | data.ToYAML | indent 16 }}
              {{- end }}
      responses:
        '200':
          description: {{ .name | strings.Title }} successfully updated
          content:
            application/json:
              schema:
                $ref: '{{ .schema }}'
              {{- if and (coll.Has . "example") (coll.Has .example "putResponse") }}
              example:
{{ .example.putResponse | data.ToYAML | indent 16 }}
              {{- end }}
        '201':
          description: {{ .name | strings.Title }} successfully created
          content:
            application/json:
              schema:
                $ref: '{{ .schema }}'
              {{- if and (coll.Has . "example") (coll.Has .example "putResponse") }}
              example:
{{ .example.putResponse | data.ToYAML | indent 16 }}
              {{- end }}
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '404':
          $ref: './schemas/errors.yaml#/responses/Error404'
        '409':
          $ref: './schemas/errors.yaml#/responses/Error409'
        '412':
          $ref: './schemas/errors.yaml#/responses/Error412'
        '422':
          $ref: './schemas/errors.yaml#/responses/Error422'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'
    {{ end }}
    {{- if coll.Has .operations "delete" }}
    delete:
      tags:
        - {{ .name | strings.Title }}
      security:
        - bearerAuth: []
      summary: Delete a {{ .name }}
      {{- if and (coll.Has . "description") (coll.Has .description "delete") }}
      description: |
{{ .description.delete | strings.TrimSpace | indent 8 }}
      {{- end }}
      operationId: delete{{ .name | strings.Title | strings.ReplaceAll " " "" }}
      parameters:
      {{- if .tenant }}
        - $ref: './schemas/parameters.yaml#/parameters/tenantID'
      {{- end }}
      {{- if .workspace }}
        - $ref: './schemas/parameters.yaml#/parameters/workspaceName'
      {{- end }}
        - $ref: './schemas/parameters.yaml#/parameters/resourceName'
        - $ref: './schemas/parameters.yaml#/parameters/ifUnmodifiedSince'
      responses:
        '202':
          description: {{ .name | strings.Title }} deletion accepted
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '404':
          $ref: './schemas/errors.yaml#/responses/Error404'
        '412':
          $ref: './schemas/errors.yaml#/responses/Error412'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'
    {{ end }}
    {{- $resource := . }}
    {{- if coll.Has . "actions" }}
    {{- range .actions }}
  /{{ $spec.version }}/{{ if $resource.tenant }}tenants/{id}/{{ end }}{{ if $resource.workspace }}workspaces/{workspace}/{{ end }}{{ if and (coll.Has . "lan") .lan }}lans/{lan}{{ end }}{{ $resource.plural | strings.Slug  }}/{name}/{{ .name | strings.Slug }}:
    post:
      tags:
        - {{ $resource.name | strings.Title }}
      security:
        - bearerAuth: []
      summary: {{ .name }} {{ $resource.name }}
      {{- if coll.Has . "description" }}
      description: |
{{ .description | strings.TrimSpace | indent 8 }}
      {{- end }}
      operationId: {{ .name | strings.Title | strings.ReplaceAll " " "" }}{{ $resource.name | strings.Title }}
      parameters:
      {{- if $resource.tenant }}
        - $ref: './schemas/parameters.yaml#/parameters/tenantID'
      {{- end }}
      {{- if $resource.workspace }}
        - $ref: './schemas/parameters.yaml#/parameters/workspaceName'
      {{- end }}
        - $ref: './schemas/parameters.yaml#/parameters/resourceName'
      responses:
        '202':
          description: action accepted
        '400':
          $ref: './schemas/errors.yaml#/responses/Error400'
        '401':
          $ref: './schemas/errors.yaml#/responses/Error401'
        '403':
          $ref: './schemas/errors.yaml#/responses/Error403'
        '404':
          $ref: './schemas/errors.yaml#/responses/Error404'
        '500':
          $ref: './schemas/errors.yaml#/responses/Error500'
    {{ end }}
    {{- end }}
  {{- end }}
{{- end }}
components:
  securitySchemes:
    $ref: './schemas/security.yaml#/securitySchemes'

  schemas:
{{- range $spec.resources }}
    {{ .name | strings.Title | strings.ReplaceAll " " "" }}Iterator:
      type: object
      required:
        - items
        - metadata
      properties:
        items:
          type: array
          items:
            $ref: '{{ .schema }}'
        metadata:
          $ref: './schemas/resource.yaml#/ResponseMetadata'
{{ end }}